config/routes.rb
Rails.application.routes.draw do
  resources :patients
  
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }


  resources :users, only: [:show]

  get 'appointments/search', to: 'appointments#search', as: 'appointments_of_date'

  resources :appointments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "appointments#index"

end

app/models/patient.rb
class Patient < ApplicationRecord
  enum sex: { masculino: 0, femenino: 1 }

  validates :sex, inclusion: { in: sexes.keys }

  belongs_to :user
  has_many :appointments, dependent: :destroy

  before_create :random_id


  def age
    today = Date.today
    birthdate = self.dob
    age = today.year - birthdate.year - ((today.month > birthdate.month || (today.month == birthdate.month && today.day >= birthdate.day)) ? 0 : 1)
    age
  end

  private
  def random_id
    begin
     self.id = SecureRandom.random_number(1_000_000_000) 
    end while User.where(id: self.id).exists?
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    @patients = current_user.patients
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = current_user.patients.build(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy!

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:name, :sex, :dob, :email)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_with(model: patient) do |form| %>
  <% if patient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="container d-flex justify-content-center align-items-center vh-85">
  <div class="card text-center">
    <div class="card-body">

      <br>
      <div>
        <%= form.label :name, style: "display: block" %>
        <%= form.text_field :name %>
      </div>
      <br>
      <div>
        <%= form.label :sex, style: "display: block" %>
        <%= form.select :sex, ['masculino', 'femenino'], {}, { class: 'form-control' } %>
      </div>
      <br>
      <div>
        <%= form.label :dob, "Date of Birth", style: "display: block" %>
        <%= form.date_field :dob %>
      </div>
      <br>
      <div>
        <%= form.label :email, style: "display: block" %>
        <%= form.text_field :email %>
      </div>
      <br>
      <div>
        <%= form.submit "Save", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/patients/_patient.html.erb
<div id="<%= dom_id patient %>">
  <p>
    <strong>Name:</strong>
    <%= patient.name %>
  </p>

  <p>
    <strong>Sex:</strong>
    <%= patient.sex %>
  </p>

  <p>
    <strong>Dob:</strong>
    <%= patient.dob %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= patient.email %>
  </p>

</div>

app/views/patients/edit.html.erb
<style>
  h1 {
    text-align: center;
  }
</style>
<h1>Editing patient</h1>

<%= render "form", patient: @patient %>

<br>

app/views/patients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%=current_user.name%> patients</h1>


<div id="patients">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Age</th>
        <th scope="col">Upd/Del</th>
      </tr>
    </thead>

    <tbody>
          <% @patients.sort_by(&:name).each do |patient| %>        
            <tr>
              <td> <%= patient.name %> </td>
              <td> <%= patient.email %> </td>
              <td> <%= patient.age %> </td>
              <td> <%= link_to "Edit", edit_patient_path(patient), class: 'btn btn-primary' %>
                   <%= link_to "Delete", patient_path(patient), class: 'btn btn-danger' %> </td>
            </tr>
        <% end %>
    </tbody>

  </table>

</div>

app/views/patients/new.html.erb
<style>
  h1 {
    text-align: center;
  }
</style>
<h1>New patient</h1>
<%= render "form", patient: @patient %>

<br>

app/views/patients/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container d-flex justify-content-center align-items-center vh-100">
  <div class="card text-center">
    <div class="card-body">
      <h1>Patient data </h1>
      <br>
      <h2> Name: <%= @patient.name %></h2>
      <h3>Sex: <%= @patient.sex %></h3>
      <h3>Age: <%= @patient.age %></h3>
      <h3>Email: <%= @patient.email %></h3>
      <br>
      <%= link_to "Edit this patient", edit_patient_path(@patient) , class: "btn btn-primary" %>
      <%= button_to "Delete this patient", @patient, method: :delete, class: 'btn btn-danger' %> </td>
    </div>
  </div>
</div>