config/routes.rb
Rails.application.routes.draw do
  resources :patients
  
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }


  resources :users, only: [:show]

  get 'appointments/search', to: 'appointments#search', as: 'appointments_of_date'

  resources :appointments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "appointments#index"

end

app/models/appointment.rb
class Appointment < ApplicationRecord

  belongs_to :user
  belongs_to :patient

  before_create :random_id

  private
  def random_id
    begin
     self.id = SecureRandom.random_number(1_000_000_000) 
    end while User.where(id: self.id).exists?
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_appointment, only: %i[show edit update destroy]

  # GET /appointments or /appointments.json
  def index
    redirect_to appointments_of_date_path(selected_date: Date.today)
  end
  
  # GET /appointments/new
  def new
    @appointment = current_user.appointments.build
    @patients = current_user.patients
  end

  # GET /appointments/1/edit
  def edit
  end

  def show
  end

  def search
    @selected_date = Date.parse(params[:selected_date])
    @appointments_of_date = Appointment.where(date: @selected_date.beginning_of_day..@selected_date.end_of_day)
  end


  # POST /appointments or /appointments.json
  def create
    @appointment = current_user.appointments.build(appointment_params)


    respond_to do |format|
      if @appointment.save
        format.html { redirect_to appointment_url(@appointment), notice: "Appointment was successfully created." }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1 or /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to appointment_url(@appointment), notice: "Appointment was successfully updated." }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1 or /appointments/1.json
  def destroy
    @appointment.destroy!

    respond_to do |format|
      format.html { redirect_to appointments_url, notice: "Appointment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:date, :time, :patient_id)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: appointment) do |form| %>
  <% if appointment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="container d-flex justify-content-center align-items-center vh-85">
  <div class="card text-center">
    <div class="card-body">
        <div>
          <%= form.label :date, style: "display: block" %>
          <%= form.date_field :date %>
        </div>
        <br>
        <div>
          <%= form.label :patient_id, style: "display: block" %>
          <%= form.collection_select(:patient_id, current_user.patients, :id, :name, prompt: "Select a patient") %>
        </div>
        <br>
        <div>
          <%= form.label :time, style: "display: block" %>
          <%= form.time_field :time %>
        </div>
        <br>
        <div>
          <%= form.submit "Book it!", class: "btn btn-primary" %>
        </div>
      </div>
  </div>
</div>

<% end %>

app/views/appointments/edit.html.erb
<style>
  h1 {
    text-align: center;
  }
</style>

<h1>Editing appointment</h1>

<%= render "form", appointment: @appointment %>

<br>

app/views/appointments/new.html.erb
<style>
  h1 {
    text-align: center;
  }
</style>
<h1>New appointment</h1><br>

<%= render "form", appointment: @appointment %>
<h1><%= link_to 'See today´s appointments', appointments_path, class: 'btn btn-primary' %></h1>
<br>

app/views/appointments/search.html.erb
<p style="color: green"><%= notice %></p>


<h3><%= "Today is #{current_date = Date.today.strftime("%d/%m/%Y")}" %></h3>

<%= form_tag(appointments_of_date_path, method: :get) do %>
  <div class="field">
    <%= label_tag :selected_date, "Search appointments of a date:" %>
    <%= date_field_tag :selected_date, params[:selected_date], type: "date" %>
    <%= submit_tag "Search", class: "btn btn-success" %>
  </div>
<% end %>

<br><br>
<% if @appointments_of_date.empty?%>

  <h2> No appointments for <%= @selected_date==Date.today ? "today" : @selected_date.strftime("%d/%m/%Y") %>! </h2>
<% else%>
  <h2>Seeing appointments of <%= @selected_date==Date.today ? "today" : @selected_date.strftime("%d/%m/%Y") %> </h2>
  <div id="appointments">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Time</th>
          <th scope="col">Patient name</th>
          <th scope="col">Patient email</th>
          <th scope="col">Upd/Del</th>
        </tr>
      </thead>

      <tbody>
          <% @appointments_of_date.sort_by(&:time).each do |appointment| %>
            <tr>
              <td> <%= appointment.time&.strftime("%H:%M") %></td>
              <td> <%= link_to appointment.patient.name, patient_path(appointment.patient), class: "text-dark" %> </td>
              <td> <%= appointment.patient.email %> </td>
              <td>
                <%= link_to 'Edit', edit_appointment_path(appointment), class: 'btn btn-primary' %>
                <%= link_to 'Delete', appointment_path(appointment) , method: :delete, class: 'btn btn-danger' %>
              </td>
            </tr>
          <% end %>     
      </tbody>
    </table>
  </div>
<% end%>

app/views/appointments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @appointment %>

<div class="container d-flex justify-content-center align-items-center vh-100">
  <div class="card text-center">
    <div class="card-body">
        <h2>Appointment with: <br><%= @appointment.patient.name %></h2>
        <br>
        <h3>Day: <%= @appointment.date.strftime("%d/%m/%Y") %></h3>
        <h3>At: <%= @appointment.time&.strftime("%H:%M") %></h3>
        <br>
        <%= link_to 'Edit', edit_appointment_path(@appointment), class: 'btn btn-primary' %>
        <%= button_to 'Delete', @appointment , method: :delete, class: 'btn btn-danger' %>
        <br>
        <%= link_to 'See today`s appointments', appointments_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>