config/routes.rb
Rails.application.routes.draw do
  resources :patients
  
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }


  resources :users, only: [:show]

  get 'appointments/search', to: 'appointments#search', as: 'appointments_of_date'

  resources :appointments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "appointments#index"

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">AppointmentsManager</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">

      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Book an appointment", new_appointment_path, class: "nav-link text-dark" %>
          </li>

          <li class="nav-item">
            <%= link_to "Add a patient", new_patient_path, class: "nav-link text-dark" %>
          </li>

          <li class="nav-item">
            <%= link_to "My patients", patients_path, class: "nav-link text-dark" %>
          </li>

          <li class="nav-item">
            <%= link_to current_user.name, current_user, class: "nav-link text-dark" %>
          </li>

          <li class="nav-item">
            <%= link_to "Log Out", destroy_user_session_path, class: "nav-link text-dark" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Log In", new_user_session_path , class: "nav-link text-dark" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link text-dark" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppointmentsRor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <%= yield %>
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>

  </body>
</html>